-- ============================================================================
-- 0001 核心基础：用户档�?+ 任务 + 审计日志 + Storage + 回收�?
--
-- 本文件是项目必需�?地基"迁移，所有后续模块均依赖此文件�?
--
-- 表清单：
--   1. profiles          �?用户档案（auth.users FK，触发器自动创建�?
--   2. tasks             �?业务任务（tenant_id 租户隔离 CRUD 示例�?
--   3. activity_logs     �?统一审计日志（append-only�?
--   4. storage.buckets   �?对象存储桶（avatars / campaign-assets / uploads�?
--   5. storage_trash     �?回收站记录（30 天自动过期）
--
-- 通用函数�?
--   set_updated_at()    �?updated_at 自动刷新触发�?
--   is_admin()          �?SECURITY DEFINER 管理员身份检�?
--   handle_new_user()   �?auth.users 注册自动创建 profile
-- ============================================================================

BEGIN;

-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? Helper Functions                                                        �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- 通用 updated_at 自动刷新
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? 1. profiles �?用户档案�?                                               �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS profiles (
  id                 UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email              TEXT,
  username           TEXT CHECK (char_length(username) <= 50),
  role               TEXT NOT NULL DEFAULT 'user'
                     CHECK (role IN ('user', 'admin')),
  plan_status        TEXT NOT NULL DEFAULT 'free'
                     CHECK (plan_status IN ('free', 'pro', 'enterprise')),
  avatar_url         TEXT,
  display_name       TEXT,
  auth_provider      TEXT NOT NULL DEFAULT 'email'
                     CHECK (auth_provider IN ('email', 'google', 'facebook', 'apple', 'anonymous')),
  provider_id        TEXT,
  device_id          TEXT,
  is_anonymous       BOOLEAN NOT NULL DEFAULT FALSE,
  email_verified     BOOLEAN NOT NULL DEFAULT FALSE,
  stripe_customer_id TEXT UNIQUE,
  phone              TEXT,
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles FORCE ROW LEVEL SECURITY;

-- 管理员身份检查（SECURITY DEFINER 绕过 RLS 递归�?
CREATE OR REPLACE FUNCTION is_admin(uid uuid)
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = uid AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- username 非空唯一（部分索引允许多 NULL�?
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_unique
  ON profiles(username) WHERE username IS NOT NULL;

-- RLS: 用户读写自己
CREATE POLICY profiles_select_own ON profiles
  FOR SELECT TO authenticated USING ((SELECT auth.uid()) = id);

CREATE POLICY profiles_update_own ON profiles
  FOR UPDATE TO authenticated USING ((SELECT auth.uid()) = id);

-- RLS: 管理员全权限
CREATE POLICY profiles_admin_all ON profiles
  FOR ALL TO authenticated USING (is_admin((SELECT auth.uid())));

-- 索引
CREATE INDEX IF NOT EXISTS idx_profiles_device_id ON profiles(device_id) WHERE device_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_provider  ON profiles(auth_provider);

-- updated_at 触发�?
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? 2. tasks �?业务任务表（CRUD 示例�?                                      �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS tasks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title       TEXT NOT NULL,
  completed   BOOLEAN NOT NULL DEFAULT false,
  tenant_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks FORCE ROW LEVEL SECURITY;

-- RLS: 租户隔离
CREATE POLICY tasks_tenant_isolation ON tasks
  FOR ALL TO authenticated
  USING (tenant_id = (SELECT auth.uid()))
  WITH CHECK (tenant_id = (SELECT auth.uid()));

-- RLS: 管理员全权限
CREATE POLICY tasks_admin_all ON tasks
  FOR ALL TO authenticated USING (is_admin((SELECT auth.uid())));

CREATE INDEX IF NOT EXISTS idx_tasks_tenant_id ON tasks(tenant_id);

CREATE TRIGGER tasks_set_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? 3. activity_logs �?统一审计日志（append-only�?                          �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS activity_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category    TEXT NOT NULL CHECK (category IN ('auth', 'admin', 'system')),
  user_id     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action      TEXT NOT NULL,
  ip          TEXT,
  metadata    JSONB NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs FORCE ROW LEVEL SECURITY;

-- RLS: 用户查看自己的认证日�?
CREATE POLICY activity_logs_user_select_own ON activity_logs
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id AND category = 'auth');

-- RLS: 管理员查�?写入所有日�?
CREATE POLICY activity_logs_admin_select ON activity_logs
  FOR SELECT TO authenticated
  USING (is_admin((SELECT auth.uid())));

CREATE POLICY activity_logs_admin_system ON activity_logs
  FOR SELECT TO authenticated
  USING (is_admin((SELECT auth.uid())) AND category = 'system');

-- RLS: 写入
CREATE POLICY activity_logs_auth_insert ON activity_logs
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id AND category = 'auth');

CREATE POLICY activity_logs_server_insert ON activity_logs
  FOR INSERT TO service_role
  WITH CHECK (true);

-- 索引
CREATE INDEX IF NOT EXISTS idx_activity_logs_category   ON activity_logs(category);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id    ON activity_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_metadata   ON activity_logs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_activity_logs_security   ON activity_logs(created_at DESC)
  WHERE category = 'system' AND action LIKE 'api_security_%';


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? Auth Trigger: 新用户注册自动创�?profile                                 �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  provider_val TEXT;
  is_oauth     BOOLEAN;
BEGIN
  provider_val := COALESCE(NEW.raw_user_meta_data->>'provider', 'email');
  is_oauth     := provider_val IN ('google', 'facebook', 'apple');

  INSERT INTO public.profiles (
    id, email, username, display_name, auth_provider, is_anonymous, email_verified
  )
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(NEW.email, '@', 1)),
    provider_val,
    COALESCE((NEW.raw_user_meta_data->>'is_anonymous')::boolean, FALSE),
    CASE WHEN is_oauth THEN TRUE ELSE FALSE END
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? 4. Supabase Storage Buckets + RLS                                       �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- 4a. avatars �?用户头像（公开读）
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars', 'avatars', true,
  2097152,
  ARRAY['image/png','image/jpeg','image/gif','image/webp']
) ON CONFLICT (id) DO NOTHING;

CREATE POLICY avatars_user_own ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  )
  WITH CHECK (
    bucket_id = 'avatars'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  );

CREATE POLICY avatars_admin_all ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'avatars' AND is_admin((SELECT auth.uid())));

CREATE POLICY avatars_public_select ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'avatars');

-- 4b. campaign-assets �?营销素材（公开读，管理员写�?
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'campaign-assets', 'campaign-assets', true,
  10485760,
  ARRAY['image/png','image/jpeg','image/gif','image/webp','video/mp4']
) ON CONFLICT (id) DO NOTHING;

CREATE POLICY campaign_assets_admin_all ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'campaign-assets'
    AND is_admin((SELECT auth.uid()))
  );

CREATE POLICY campaign_assets_public_select ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'campaign-assets');

-- 4c. uploads �?私有文件（用户路径隔离）
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'uploads', 'uploads', false,
  52428800,
  NULL
) ON CONFLICT (id) DO NOTHING;

CREATE POLICY uploads_user_own ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'uploads'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  )
  WITH CHECK (
    bucket_id = 'uploads'
    AND (storage.foldername(name))[1] = (SELECT auth.uid())::text
  );

CREATE POLICY uploads_admin_all ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'uploads' AND is_admin((SELECT auth.uid())));

-- 4d. audit-archives �?审计日志冷归档（私有桶，仅管理员�?
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'audit-archives', 'audit-archives', false,
  52428800,
  ARRAY['application/json']
) ON CONFLICT (id) DO NOTHING;

-- 4e. RESTRICTIVE 加固策略（AND 逻辑，与 permissive 策略取交集）
CREATE POLICY storage_scope_restrict ON storage.objects
  AS RESTRICTIVE
  FOR ALL
  TO public
  USING (bucket_id IN ('avatars', 'campaign-assets', 'uploads', 'audit-archives'))
  WITH CHECK (bucket_id IN ('avatars', 'campaign-assets', 'uploads', 'audit-archives'));

CREATE POLICY campaign_assets_restrict_delete ON storage.objects
  AS RESTRICTIVE
  FOR DELETE
  TO public
  USING (
    bucket_id != 'campaign-assets'
    OR is_admin((SELECT auth.uid()))
  );

CREATE POLICY uploads_restrict_anon ON storage.objects
  AS RESTRICTIVE
  FOR ALL
  TO anon
  USING (bucket_id != 'uploads')
  WITH CHECK (bucket_id != 'uploads');


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? 5. storage_trash �?回收站记录（30 天自动过期）                           �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

CREATE TABLE IF NOT EXISTS storage_trash (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  original_bucket TEXT NOT NULL,
  original_path   TEXT NOT NULL,
  trash_path      TEXT NOT NULL,
  file_name       TEXT NOT NULL,
  mime_type       TEXT,
  file_size       BIGINT NOT NULL DEFAULT 0,
  deleted_by      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '30 days',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE storage_trash ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage_trash FORCE ROW LEVEL SECURITY;

CREATE POLICY storage_trash_admin_all ON storage_trash
  FOR ALL TO authenticated
  USING (is_admin((SELECT auth.uid())))
  WITH CHECK (is_admin((SELECT auth.uid())));

CREATE INDEX IF NOT EXISTS idx_storage_trash_expires ON storage_trash(expires_at)
  WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_storage_trash_created ON storage_trash(created_at DESC);


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- �? Seed: 内置管理�?profiles 记录                                           �?
-- �? 固定 UUID: 9e638ba2-41aa-4434-a68b-6bd9f7ed0963                        �?
-- ╚══════════════════════════════════════════════════════════════════════════╝

-- First create the auth user so the FK constraint on profiles is satisfied
INSERT INTO auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, confirmation_sent_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, aud, role)
SELECT
  '9e638ba2-41aa-4434-a68b-6bd9f7ed0963',
  '00000000-0000-0000-0000-000000000000',
  'admin@hehe.app',
  crypt('HeHeAdmin2024', gen_salt('bf')),
  now(),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{}',
  now(),
  now(),
  'authenticated',
  'authenticated'
WHERE NOT EXISTS (SELECT 1 FROM auth.users WHERE id = '9e638ba2-41aa-4434-a68b-6bd9f7ed0963');
INSERT INTO public.profiles (id, username, display_name, role, plan_status, auth_provider, is_anonymous, email_verified)
VALUES (
  '9e638ba2-41aa-4434-a68b-6bd9f7ed0963'::uuid,
  'admin',
  'Administrator',
  'admin',
  'pro',
  'email',
  false,
  true
) ON CONFLICT (id) DO UPDATE SET
  role = 'admin',
  plan_status = 'pro',
  updated_at = NOW();

COMMIT;
