-- ====================================================================
-- 0001 核心基础表与 RLS 数据安全隔离策略
-- 依赖：无（首个迁移）
-- 表名：profiles, campaigns, tasks, activity_logs
-- ====================================================================

-- -------------------------------------------------------------
-- 1. 用户档案表 (profiles)
--    Supabase Auth 用户注册后通过触发器自动创建记录
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "profiles" (
  "id"                 UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "username"           TEXT UNIQUE NOT NULL,
  "role"               TEXT NOT NULL DEFAULT 'user' CHECK ("role" IN ('user', 'admin')),
  "plan_status"        TEXT NOT NULL DEFAULT 'free' CHECK ("plan_status" IN ('free', 'pro', 'enterprise')),
  "created_at"         TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;

-- 允许用户 SELECT 自己的 profile
CREATE POLICY "profiles_select_own" ON "profiles"
  FOR SELECT TO authenticated USING (auth.uid() = id);

-- 允许用户 UPDATE 自己的 profile
CREATE POLICY "profiles_update_own" ON "profiles"
  FOR UPDATE TO authenticated USING (auth.uid() = id);

-- 允许管理员查看与管理所有 profiles
CREATE POLICY "profiles_admin_all" ON "profiles"
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM "profiles" WHERE id = auth.uid() AND "role" = 'admin'
    )
  );

-- -------------------------------------------------------------
-- 2. 营销活动配置表 (campaigns)
--    H5 营销页核心数据，游客可读，管理员可写
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "campaigns" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "subdomain"   TEXT UNIQUE NOT NULL,
  "title"       TEXT NOT NULL,
  "subtitle"    TEXT NOT NULL,
  "badge"       TEXT NOT NULL,
  "color_from"  TEXT NOT NULL DEFAULT 'from-purple-600',
  "color_to"    TEXT NOT NULL DEFAULT 'to-indigo-600',
  "created_at"  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE "campaigns" ENABLE ROW LEVEL SECURITY;

-- 所有人（含游客）都可以读取活动配置以渲染营销 H5 页面
CREATE POLICY "campaigns_read_public" ON "campaigns"
  FOR SELECT TO public USING (true);

-- 仅管理员可以进行增删改查
CREATE POLICY "campaigns_admin_all" ON "campaigns"
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM "profiles" WHERE id = auth.uid() AND "role" = 'admin'
    )
  );

-- -------------------------------------------------------------
-- 3. 业务任务表 (tasks)
--    任务看板 Demo，tenant_id 实现行级数据隔离
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "tasks" (
  "id"          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "title"       TEXT NOT NULL,
  "completed"   BOOLEAN NOT NULL DEFAULT false,
  "tenant_id"   UUID NOT NULL, -- 项目数据隔离 ID (关联用户 ID)
  "created_at"  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE "tasks" ENABLE ROW LEVEL SECURITY;

-- 行级隔离策略：用户只允许操作自己项目的数据
CREATE POLICY "tasks_tenant_isolation" ON "tasks"
  FOR ALL TO authenticated
  USING ("tenant_id" = auth.uid())
  WITH CHECK ("tenant_id" = auth.uid());

-- 允许管理员查看与管理所有的业务任务
CREATE POLICY "tasks_admin_all" ON "tasks"
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM "profiles" WHERE id = auth.uid() AND "role" = 'admin'
    )
  );

-- -------------------------------------------------------------
-- 4. 统一活动日志表 (activity_logs)
--    合并原 audit_logs + user_login_logs，用 category 区分类型
--    metadata JSONB 灵活存储各类日志的扩展字段
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "activity_logs" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category"    TEXT NOT NULL
                CHECK ("category" IN ('auth', 'admin', 'system')),
  "user_id"     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  "action"      TEXT NOT NULL,
  "ip"          TEXT,
  "metadata"    JSONB NOT NULL DEFAULT '{}',
  "created_at"  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE "activity_logs" ENABLE ROW LEVEL SECURITY;

-- 用户可查看自己的认证日志
CREATE POLICY "activity_logs_user_select_own" ON "activity_logs"
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id AND category = 'auth');

-- 管理员可查看所有日志
CREATE POLICY "activity_logs_admin_select" ON "activity_logs"
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- 认证用户可写入自己的认证日志（登录/注册等）
CREATE POLICY "activity_logs_auth_insert" ON "activity_logs"
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id AND category = 'auth');

-- 服务端可写入任意日志（受信任 Server 直写）
CREATE POLICY "activity_logs_server_insert" ON "activity_logs"
  FOR INSERT TO service_role
  WITH CHECK (true);

-- -------------------------------------------------------------
-- 索引优化
-- -------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "idx_activity_logs_category" ON "activity_logs"(category);
CREATE INDEX IF NOT EXISTS "idx_activity_logs_user_id" ON "activity_logs"(user_id);
CREATE INDEX IF NOT EXISTS "idx_activity_logs_created_at" ON "activity_logs"(created_at DESC);
